name       : haskell-hackage-security
version    : 0.6.2.3
release    : 7
source     :
    # Revision 3
    - https://hackage.haskell.org/package/hackage-security-0.6.2.3/hackage-security-0.6.2.3.tar.gz : 52ee0576971955571d846b8e6c09638f89f4f7881f4a95173e44ccc0d856a066
license    : BSD-3-Clause
component  : programming.haskell
summary    : The hackage security library provides both server and client utilities for securing the Hackage package server
description: |
    The hackage security library provides both server and client utilities for securing the Hackage package server
builddeps  :
    - ghc-devel
    - haskell-cabal-syntax
    - haskell-regex-base-devel
    - haskell-lukko-devel
    - haskell-base16-bytestring-devel
    - haskell-base64-bytestring-devel
    - haskell-cryptohash-sha256-devel
    - haskell-ed25519-devel
    - haskell-network-devel
    - haskell-network-uri-devel
    - haskell-tar-devel
    - haskell-zlib-devel
rundeps    :
    - devel :
        - haskell-cabal-syntax
        - haskell-regex-base-devel
        - haskell-lukko-devel
        - haskell-base16-bytestring-devel
        - haskell-base64-bytestring-devel
        - haskell-cryptohash-sha256-devel
        - haskell-ed25519-devel
        - haskell-network-devel
        - haskell-network-uri-devel
        - haskell-tar-devel
        - haskell-zlib-devel
setup      : |
    cp $pkgfiles/3.cabal hackage-security.cabal
    %haskell_configure -f lukko
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
