name       : haskell-hackage-security
version    : 0.5.3.0
release    : 6
source     :
    - https://hackage.haskell.org/package/hackage-security-0.5.3.0/hackage-security-0.5.3.0.tar.gz : db986e17e9265aa9e40901690815b890b97d53159eb24d0a6cafaa7c18577c21
license    : BSD-3-Clause
component  : programming.haskell
summary    : The hackage security library provides both server and client utilities for securing the Hackage package server
description: |
    The hackage security library provides both server and client utilities for securing the Hackage package server
builddeps  :
    - haskell-cabal-install
    - haskell-base16-bytestring-devel
    - haskell-base64-bytestring-devel
    - haskell-cryptohash-sha256-devel
    - haskell-ed25519-devel
    - haskell-network-devel
    - haskell-network-uri-devel
    - haskell-tar-devel
    - haskell-zlib-devel
rundeps    :
    - devel:
        - haskell-base16-bytestring-devel
        - haskell-base64-bytestring-devel
        - haskell-cryptohash-sha256-devel
        - haskell-ed25519-devel
        - haskell-network-devel
        - haskell-network-uri-devel
        - haskell-tar-devel
        - haskell-zlib-devel
networking : yes
setup      : |
    sed -i "s|< 4.12|< 4.13|g" hackage-security.cabal # base
    sed -i "s|< 2.4|< 2.5|g" hackage-security.cabal   # cabal
    sed -i "s|< 0.6|< 0.7|g" hackage-security.cabal   # containers
    sed -i "s|< 2.7|< 3.2|g" hackage-security.cabal   # network
    %cabal_configure -fbase48 -f-lukko
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
