name       : haskell-hackage-security
version    : 0.5.2.2
release    : 1
source     :
    - http://hackage.haskell.org/package/hackage-security-0.5.2.2/hackage-security-0.5.2.2.tar.gz : 507a837851264a774c8f4d400f798c3dac5be11dc428fe72d33ef594ca533c41
license    : BSD-3-Clause
component  : programming
summary    : The hackage security library provides both server and client utilities for securing the Hackage package server
description: |
    The hackage security library provides both server and client utilities for securing the Hackage package server
builddeps  :
    - ghc
    - haskell-base16-bytestring
    - haskell-base64-bytestring
    - haskell-cryptohash-sha256
    - haskell-ed25519
    - haskell-mtl
    - haskell-network
    - haskell-network-uri
    - haskell-parsec
    - haskell-tar
    - haskell-zlib
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 hackage-security-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/hackage-security-$version.conf
