name       : haskell-hackage-security
version    : 0.5.3.0
release    : 5
source     :
    - https://hackage.haskell.org/package/hackage-security-0.5.3.0/hackage-security-0.5.3.0.tar.gz : db986e17e9265aa9e40901690815b890b97d53159eb24d0a6cafaa7c18577c21
license    : BSD-3-Clause
component  : programming.haskell
summary    : The hackage security library provides both server and client utilities
    for securing the Hackage package server
description: |
    The hackage security library provides both server and client utilities for securing the Hackage package server
builddeps  :
    - haskell-cabal-install
    - haskell-base16-bytestring
    - haskell-base64-bytestring
    - haskell-cryptohash-sha256
    - haskell-ed25519
    - haskell-mtl
    - haskell-network-devel
    - haskell-network-uri
    - haskell-old-locale
    - haskell-parsec
    - haskell-tar
    - haskell-zlib
setup      : |
    sed -i "s|2.7|2.8|g" hackage-security.cabal
    sed -i "s|4.8|4.9|g" hackage-security.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
